---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
dictionaryDefinitions:
  - name: nvim-spell
    path: '~/.config/nvim/spell/en.utf-8.add'
    addWords: true
  - name: cspell
    path: '~/.config/nvim/spell/cspell.txt'
    addWords: true
dictionaries:
  - nvim-spell
  - cspell
