#!/bin/bash
BRANCH=$(git branch | grep '^\*' | cut -b3- | cut -f1,2 -d'-')
BRANCHTYPE=${BRANCH%/*}
FILE=$(cat "$1")
CLEAN=$(cat "$1" | grep NO_COMMIT)

if [[ -n $CLEAN ]]; then
    printf "[0;31mno cake for you[0m\n"
    exit 1
fi

FIRSTLINE=$(sed -n "1p" $1)
if [[ -z $FIRSTLINE ]]; then
    IDS=$(~/dotfiles/scripts/product-board.sh)
    if [[ -n $IDS ]]; then
        echo -e "$BRANCHTYPE: \n\n$IDS $FILE" > "$1"
    else
        echo -e "$BRANCHTYPE: $FILE" > "$1"
    fi
fi
