require("spellsitter").setup {
    enable = {
        "lua",
        "go",
        "rust",
        "python",
        "vim",
        "typescript",
        "javascript",
        "toml",
        "typescriptreact",
        "json",
        "dockerfile",
        "yaml",
        "bash",
        "sh",
        "markdown",
        "prisma",
    },
}
