#!/bin/bash

### colors ###
RED='\e[0;31m'
GRN='\e[0;32m'
YEL='\e[33m'
CYN='\e[36m'
LGR='\e[37m'
DGR='\e[90m'
WHT='\e[97m'
NC='\e[0m' # No Color

export PATH=${PATH}:$HOME/.gem/ruby/2.4.0/bin
export PATH=${PATH}:$HOME/.npm-global/bin

# ssh
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > ~/.ssh-agent-thing
fi
if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval "$(<~/.ssh-agent-thing)"
fi


#screenfetch -t
# export PS1="\[$(tput setaf 6)\]╔═╡\e[46m \[$(tput setaf 16)\]サイコパス \e[0m\[$(tput setaf 6)\]│ \[$(tput setaf 0)\]\W\n\[$(tput setaf 6)\]╚═════╾ \[$(tput sgr0)\]"

PROMPT_COMMAND=${PROMPT_COMMAND:+$PROMPT_COMMAND; }'printf "\033_%s\033\\" "${PWD##*/}"'
GIT_PROMPT_THEME=Solarized_Extravagant

